services:
  web:
    volumes:
      - ./web:/app
    working_dir: /app
    environment:
      - MODE=dev
      - PYTHONPATH=/src

  auth:
    volumes:
      - ./auth:/app
    environment:
      - MODE=dev

  admin:
    volumes:
      - ./admin:/app
    environment:
      - MODE=dev
